test

diff --git a/frontend/.husky/pre-commit b/frontend/.husky/pre-commit
--- a/frontend/.husky/pre-commit
+++ b/frontend/.husky/pre-commit
@@ -1,11 +1,20 @@
 #!/bin/sh
 . "$(dirname "$0")/_/husky.sh"
 
-if ! pip list | grep -E 'black|flake8'; then
-    echo "Unable to find Black and Flake8 installations"
+fail=0
+
+if ! pip list | grep -E 'black'; then
+    echo -e 'Unable to find \033[1mBlack\033[0m, please install Black locally.'
+    fail=1
+fi
+
+if ! pip list | grep -E 'flake8'; then
+    echo -e 'Unable to find \033[1mFlake8\033[0m, please install Flake8 locally.'
+    fail=1
+fi
+
+if (( $fail > 0 )); then
     exit 1
-else
-    echo "Found both!"
 fi
 
 cd frontend
